/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_HaikuGraphicsConfig */

#ifndef _Included_sun_awt_HaikuGraphicsConfig
#define _Included_sun_awt_HaikuGraphicsConfig
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: defaultBufferCaps */
/* Inaccessible static: defaultImageCaps */
/* Inaccessible static: bufferCaps */
/* Inaccessible static: imageCaps */
/*
 * Class:     sun_awt_HaikuGraphicsConfig
 * Method:    getWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_HaikuGraphicsConfig_getWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_HaikuGraphicsConfig
 * Method:    getHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_HaikuGraphicsConfig_getHeight
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
