/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_awt_HaikuGraphicsDevice */

#ifndef _Included_sun_awt_HaikuGraphicsDevice
#define _Included_sun_awt_HaikuGraphicsDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_awt_HaikuGraphicsDevice_TYPE_RASTER_SCREEN
#define sun_awt_HaikuGraphicsDevice_TYPE_RASTER_SCREEN 0L
#undef sun_awt_HaikuGraphicsDevice_TYPE_PRINTER
#define sun_awt_HaikuGraphicsDevice_TYPE_PRINTER 1L
#undef sun_awt_HaikuGraphicsDevice_TYPE_IMAGE_BUFFER
#define sun_awt_HaikuGraphicsDevice_TYPE_IMAGE_BUFFER 2L
/*
 * Class:     sun_awt_HaikuGraphicsDevice
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sun_awt_HaikuGraphicsDevice_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     sun_awt_HaikuGraphicsDevice
 * Method:    getWorkspaceCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_HaikuGraphicsDevice_getWorkspaceCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     sun_awt_HaikuGraphicsDevice
 * Method:    getCurrentWorkspace
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sun_awt_HaikuGraphicsDevice_getCurrentWorkspace
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
